
version: 2
models:
  - name: of_fcubs_accounts
    description: Aggregates account details, including account status, holder information, and credit line details based on Open Finance standards.
    columns:
      - name: account_id
        description: A unique and immutable identifier produced by the financial institution to identify the account resource. This identifier has no meaning to the account owner (User 1).
        tests:
          - not_null
          - unique
      - name: customer_id
        description: A unique and immutable identifier used to identify the customer resource. This identifier has no meaning to the account owner.
        # tests:
          # - not_null
      - name: product_id
        description: Identifier within the financial institution for the product. Must be unique in the organisation.
      - name: account_type
        description: Specifies the type of account (Retail, SME, Corporate).
      - name: account_subtype
        description: Specifies the sub-type of account (product family group). Values include CurrentAccount, Savings.
      - name: description
        description: Descriptive name for the product associated with the account.
      - name: nickname
        description: The nickname of the account, assigned by User 1 to provide an additional and easier means of identification of the account at the financial institution.
      - name: status
        description: Specifies the status of the account resource in code form. Allowed values are Active, Inactive, Dormant, Unclaimed, Deceased, Suspended, Closed.
      - name: status_update_datetime
        description: Date and time at which the resource status was updated.
      - name: account_number
        description: Identification for the account assigned by the financial institution based on the Account Scheme Name. This identification is known by the User 1 account owner.
        tests:
          - not_null
          - unique
      - name: account_iban
        description: IBAN of the account. Refer to ISO Standard 13616 for more details.
      - name: opening_date
        description: Date on which the account and its related basic services by the financial institution started to be operational for User 1.
      - name: maturity_date
        description: Fixed Term Savings Account MaturityDate is the date on which the savings mature and the balance can be withdrawn by the User without penalty.
      - name: total_balance
        description: Total balance available in the account.
      - name: credit_debit_indicator
        description: Indicates whether the balance of the account is a credit or a debit balance.
      - name: currency
        description: A 3 character alphabetic code allocated to a currency under an international currency identification scheme, as described in the latest edition of the international standard ISO 4217 'Codes for the representation of currencies and funds'.
      - name: last_updated
        description: Indicates the date (and time) that the account balance was checked.
      - name: max_overdraft_limit
        description: Maximum overdraft limit set for the account.
      - name: notes
        description: Notes providing more information on the account.
      - name: account_holder_name
        description: The Account Holder Name is the name or names of the Beneficiary account owner(s) represented at the account level, as displayed by the Creditor Agent's online channels and as provided by the Beneficiary to the customer when adding the Beneficiary in the Beneficiary list. Note, the Account Holder Name is not the product name or the nickname of the account.
      - name: account_holder_short_name
        description: The Beneficiary account holder nick name.
      - name: credit_line_type
        description: Specifies the type of credit line provided to the account. Allowed values include Available, Credit, Emergency, Pre-Agreed, Temporary.
      - name: credit_line_included
        description: Boolean flag to indicate whether or not a credit line is included in the balance of the account.

  - name: of_fcubs_person
    description: Contains details of customers, including personal and professional information, aligned with Open Finance standards.
    columns:
      - name: customer_id
        description: A unique and immutable identifier used to identify the customer resource. This identifier has no meaning to the account owner.
        tests:
          - not_null
          - unique
      - name: type
        description: Type of customer account (e.g., Individual, Business).
      - name: account_role
        description: Specifies the Party's role with respect to the related account. Allowed values include Administrator, Beneficiary, CustodianForMinor, Granter, LegalGuardian, OtherParty, PowerOfAttorney, Principal, Protector, RegisteredShareholderName, SecondaryOwner, SeniorManagingOfficial, Settlor, SuccessorOnDeath.
      - name: given_name
        description: Given name of the Party. Given name (also called forename) is used to differentiate from the surname or family name.
      - name: full_name
        description: The full name of the account holder, as it appears on the account, as a single string. Used where LFIs hold the account name as a single value.
      - name: also_known_as
        description: Alias or nickname of the customer for easier identification.
      - name: birthdate
        description: Date of birth of the Party.
      - name: address_id
        description: Identifier for the customer's address.
      - name: short_address
        description: Shortened form of the customer's address.
      - name: address_line_1
        description: The primary line of the customer's address.
      - name: address_city
        description: City where the customer resides.
      - name: address_state
        description: State where the customer resides.
      - name: address_postcode
        description: Postal code of the customer's address.
      - name: address_country
        description: Country where the customer resides.
      - name: address_type
        description: Type of the customer's address (e.g., Residential, Business).
      - name: source_income_wealth
        description: The customer source of income.
      - name: income
        description: The customer salary.
      - name: nationality
        description: The customer nationality, standardised where possible using a recognised three-character code set such as ISO 3166.
      - name: phone_number
        description: The customer mobile number.
      - name: email_address
        description: The customer email address for communication.
      - name: status
        description: Current status of the customer account (e.g., Active, Inactive).
      - name: salutation
        description: The customer salutation.
      - name: preferred_language
        description: The primary language of the customer, standardised where possible using a recognised three-character code set such as ISO 639.
      - name: power_of_attorney
        description: Indicator that labels whether the customer is subject to a power of attorney arrangement.
      - name: salary_transfer
        description: Indicator that labels whether the customer receives their salary in the associated account.
      - name: profession
        description: The customer profession.
      - name: last_updated
        description: The date at which the customer data was last updated.
      - name: employer_name
        description: The employer name of the customer.
      - name: date_of_joining
        description: The date from which the customer was employed by their employer.
      - name: document_type
        description: Type of identification document provided by the customer.
      - name: personal_number
        description: An identifier that is assigned to the customer and is not limited to being used in one document, for example a national identification number, personal identity number, citizen number, social security number, driver number, account number, customer number, licensee number, etc.
      - name: document_expiry_date
        description: Expiry date of the customer's identification document.

  - name: of_fcubs_product
    description: Provides product details linked to customer accounts as per Open Finance standards.
    columns:
      - name: product_id
        description: Identifier within the financial institution for the product. Must be unique in the organisation.
        tests:
          - not_null
          - unique
      - name: name
        description: Descriptive name for the product.
      - name: type
        description: Descriptive code for the product.
      - name: islamic
        description: A flag to denote if the Product is an Islamic product. 
