-- USER_CONSENTS TABLE SCHEMA
CREATE TABLE IF NOT EXISTS USER_CONSENTS (
    USER_ID INT PRIMARY KEY,
    CONSENT_ID INT NOT NULL,
    CONSENT_GRANTED_DATE DATE NOT NULL,
    CONSENT_STATUS VARCHAR(50) NOT NULL
    );

-- ACCOUNTS TABLE SCHEMA
CREATE TABLE IF NOT EXISTS ACCOUNTS (
    ACCOUNT_ID INT PRIMARY KEY,
    USER_ID INT NOT NULL,
    ACCOUNT_TYPE VARCHAR(50) NOT NULL,
    ACCOUNT_STATUS VARCHAR(50) NOT NULL,
    ACCOUNT_BALANCE DECIMAL(15, 2) NOT NULL,
    BANK_NAME VARCHAR(100) NOT NULL
    --FOREIGN KEY (USER_ID) REFERENCES USER_CONSENTS(USER_ID)
    );

-- TRANSACTIONS TABLE SCHEMA
CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    TRANSACTION_ID INT PRIMARY KEY,
    ACCOUNT_ID INT NOT NULL,
    TRANSACTION_AMOUNT DECIMAL(15, 2) NOT NULL,
    TRANSACTION_DATE DATE NOT NULL,
    TRANSACTION_TYPE VARCHAR(50) NOT NULL
    --FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ACCOUNT_ID)
    );
