marquez_local:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres_database
      # host: localhost
      port: 5432
      user: sampatel3
      password: pw
      dbname: marquezdb
      schema: openfinance
